# Generated by Django 6.0.6 on 2026-06-24 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age_group', models.CharField(choices=[('Below 25', 'Below 25 years'), ('25-34', '25–34 years'), ('35-44', '35–44 years'), ('45-54', '45–54 years'), ('Above 54', 'Above 54 years')], max_length=20)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced/Separated'), ('Widowed', 'Widowed')], max_length=20)),
                ('household_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('main_occupation', models.CharField(choices=[('Onion retailing', 'Onion retailing'), ('General produce trading', 'General produce trading'), ('Farming', 'Farming'), ('Salaried employment', 'Salaried employment'), ('Other', 'Other')], max_length=50)),
                ('other_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('member_of_group', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('access_to_credit', models.BooleanField(default=False)),
                ('credit_source', models.CharField(blank=True, choices=[('SACCO', 'SACCO'), ('Commercial bank', 'Commercial bank'), ('Microfinance', 'Microfinance institution'), ('Friends/Relatives', 'Friends/Relatives'), ('Traders association', "Traders' association"), ('Money lender', 'Money lender'), ('Other', 'Other')], max_length=50, null=True)),
                ('years_schooling', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('education_level', models.CharField(choices=[('No formal', 'No formal education'), ('Primary', 'Primary education'), ('Secondary', 'Secondary education'), ('Tertiary', 'Tertiary institution'), ('University', 'University education')], max_length=50)),
                ('years_in_onion_retailing', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('business_nature', models.CharField(choices=[('Stall owner', 'Stall owner'), ('Stall renter', 'Stall renter'), ('Mobile vendor', 'Mobile vendor'), ('Assistant', 'Assistant/Employee'), ('Other', 'Other')], max_length=50)),
                ('other_business_nature', models.CharField(blank=True, max_length=100, null=True)),
                ('onion_source', models.CharField(choices=[('Farmers', 'Directly from farmers'), ('Wholesale', 'Wholesale markets (e.g., Kisenyi)'), ('Upcountry', 'Upcountry traders'), ('Imported', 'Imported onions')], max_length=100)),
                ('major_customers', models.CharField(blank=True, max_length=200)),
                ('weekly_purchase_kg', models.PositiveIntegerField()),
                ('avg_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_sales_kg', models.PositiveIntegerField()),
                ('weekly_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekly_transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stall_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('market_dues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packaging', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loading_offloading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('casual_labour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_costs_desc', models.CharField(blank=True, max_length=200)),
                ('profitability_opinion', models.CharField(choices=[('Very profitable', 'Very profitable'), ('Moderately', 'Moderately profitable'), ('Slightly', 'Slightly profitable'), ('Not profitable', 'Not profitable')], max_length=50)),
                ('experience_spoilage', models.BooleanField(default=True)),
                ('weekly_spoilage_kg', models.PositiveIntegerField(default=0)),
                ('spoilage_percentage', models.CharField(choices=[('<5%', 'Less than 5%'), ('5-10%', '5–10%'), ('11-20%', '11–20%'), ('21-30%', '21–30%'), ('>30%', 'Above 30%')], max_length=20)),
                ('money_loss_spoilage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spoilage_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('causes_spoilage', models.JSONField(default=list)),
                ('has_storage', models.BooleanField(default=False)),
                ('storage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('onions_stay_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('received_training', models.BooleanField(default=False)),
                ('spoilage_effects', models.JSONField(default=list)),
                ('strategies', models.JSONField(default=list)),
                ('other_strategy', models.CharField(blank=True, max_length=200)),
                ('major_challenges', models.TextField(blank=True)),
                ('measures_to_reduce', models.TextField(blank=True)),
                ('other_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
