# Generated by Django 6.0.6 on 2026-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnionRetailSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('age_group', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('household_size', models.PositiveIntegerField()),
                ('main_occupation', models.CharField(max_length=100)),
                ('other_occupation', models.CharField(blank=True, max_length=255)),
                ('member_of_group', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('access_to_credit', models.BooleanField(default=False)),
                ('credit_source', models.CharField(blank=True, max_length=100)),
                ('years_schooling', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('years_in_onion_retailing', models.PositiveIntegerField(blank=True, null=True)),
                ('business_nature', models.CharField(blank=True, max_length=100)),
                ('onion_source', models.CharField(blank=True, max_length=100)),
                ('major_customers', models.CharField(blank=True, max_length=100)),
                ('weekly_purchase_kg', models.FloatField(blank=True, null=True)),
                ('avg_purchase_price', models.FloatField(blank=True, null=True)),
                ('avg_selling_price', models.FloatField(blank=True, null=True)),
                ('weekly_sales_kg', models.FloatField(blank=True, null=True)),
                ('weekly_revenue', models.FloatField(blank=True, null=True)),
                ('weekly_transport_cost', models.FloatField(blank=True, null=True)),
                ('stall_rent', models.FloatField(default=0)),
                ('market_dues', models.FloatField(default=0)),
                ('packaging_materials', models.FloatField(default=0)),
                ('loading_offloading', models.FloatField(default=0)),
                ('casual_labour', models.FloatField(default=0)),
                ('storage_expenses', models.FloatField(default=0)),
                ('other_cost_description', models.CharField(blank=True, max_length=255)),
                ('other_cost_amount', models.FloatField(default=0)),
                ('profitability_opinion', models.CharField(blank=True, max_length=100)),
                ('experience_spoilage', models.BooleanField(default=False)),
                ('weekly_spoilage_kg', models.FloatField(blank=True, null=True)),
                ('spoilage_percentage', models.CharField(blank=True, max_length=50)),
                ('money_loss_spoilage', models.FloatField(blank=True, null=True)),
                ('spoilage_stage', models.CharField(blank=True, max_length=100)),
                ('causes_spoilage', models.JSONField(default=list)),
                ('storage_facility', models.BooleanField(default=False)),
                ('storage_type', models.CharField(blank=True, max_length=100)),
                ('storage_type_other', models.CharField(blank=True, max_length=255)),
                ('onions_stay_duration', models.CharField(blank=True, max_length=100)),
                ('received_training', models.BooleanField(default=False)),
                ('spoilage_effects', models.JSONField(default=list)),
                ('strategies', models.JSONField(default=list)),
                ('other_strategy', models.CharField(blank=True, max_length=255)),
                ('major_challenges', models.TextField(blank=True)),
                ('measures_to_reduce', models.TextField(blank=True)),
                ('other_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
