from Edc.models import OnionRetailSurvey
from rest_framework.generics import CreateAPIView, ListCreateAPIView
from .serializers import OnionRetailSurveySerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response


class OnionRetailSurveyCreateView(ListCreateAPIView):
    queryset = OnionRetailSurvey.objects.all()
    serializer_class = OnionRetailSurveySerializer


@api_view(['GET'])
def view_survey_data(request):
    surveys= OnionRetailSurvey.objects.all()
    serializer = OnionRetailSurveySerializer(
        surveys,
        many=True
    )
    return Response({'data': serializer.data})

from django.http import HttpResponse
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from datetime import datetime


def download_survey_data(request):
    wb = Workbook()

    # ==========================
    # Sheet 1: Survey Data
    # ==========================
    ws = wb.active
    ws.title = "Survey Data"

    fields = [field.name for field in OnionRetailSurvey._meta.fields]

    # Header styling
    header_fill = PatternFill(
        start_color="2E7D32",
        end_color="2E7D32",
        fill_type="solid"
    )

    header_font = Font(
        bold=True,
        color="FFFFFF"
    )

    center = Alignment(
        horizontal="center",
        vertical="center"
    )

    # Write headers
    for col, field in enumerate(fields, start=1):
        cell = ws.cell(row=1, column=col)
        cell.value = field.replace("_", " ").title()
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = center

    # Freeze header
    ws.freeze_panes = "A2"

    surveys = OnionRetailSurvey.objects.all()

    for row, survey in enumerate(surveys, start=2):

        for col, field in enumerate(fields, start=1):

            value = getattr(survey, field)

            # Many-to-many / lists / JSON fields
            if isinstance(value, list):
                value = ", ".join(map(str, value))

            elif isinstance(value, dict):
                value = str(value)

            # Datetime formatting
            elif hasattr(value, "strftime"):
                value = value.strftime("%Y-%m-%d %H:%M")

            cell = ws.cell(row=row, column=col)
            cell.value = value

            # Alternate row colour
            if row % 2 == 0:
                cell.fill = PatternFill(
                    start_color="F8F9FA",
                    end_color="F8F9FA",
                    fill_type="solid"
                )

    # Autofilter
    ws.auto_filter.ref = ws.dimensions

    # Auto-size columns
    for column in ws.columns:
        length = max(
            len(str(cell.value)) if cell.value is not None else 0
            for cell in column
        )

        letter = get_column_letter(column[0].column)

        ws.column_dimensions[letter].width = min(length + 4, 45)

    # ==========================
    # Sheet 2: Summary
    # ==========================
    summary = wb.create_sheet("Summary")

    summary["A1"] = "Emily Mwagale Onion Retail Survey"
    summary["A1"].font = Font(size=16, bold=True)

    summary["A3"] = "Total Records"
    summary["B3"] = surveys.count()

    summary["A4"] = "Export Date"
    summary["B4"] = datetime.now().strftime("%d %B %Y")

    summary["A5"] = "Export Time"
    summary["B5"] = datetime.now().strftime("%H:%M")

    summary["A7"] = "Generated By"
    summary["B7"] = "EDC Data Collection System"

    summary["A9"] = "Purpose"
    summary["B9"] = (
        "Survey of onion retailers in Nakasero Market "
        "conducted for academic research."
    )

    for cell in ["A1", "A3", "A4", "A5", "A7", "A9"]:
        summary[cell].font = Font(bold=True)

    summary.column_dimensions["A"].width = 25
    summary.column_dimensions["B"].width = 60

    # ==========================
    # Download
    # ==========================
    response = HttpResponse(
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

    filename = datetime.now().strftime(
        "Nakasero_Onion_Retail_Survey_%Y%m%d_%H%M.xlsx"
    )

    response["Content-Disposition"] = f'attachment; filename="{filename}"'

    wb.save(response)

    return response